version: '3.4'

services:
  hc.api:
    image: ${DOCKER_REGISTRY-}hcapi
    build:
      context: .
      dockerfile: HC.API/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - postgresdb
      - rabbitmq

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hiscarydbef
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # TODO: inject config related stuff from a separate CI/CD injection mechanism
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data:
