version: '3.4'

services:
  hc.api:
    image: ${DOCKER_REGISTRY-}hcapi
    build:
      context: .
      dockerfile: HC.API/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hiscarydbef
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
