name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Restore dependencies
        working-directory: server
        run: dotnet restore Hiscaries.sln

      - name: Build
        working-directory: server
        run: dotnet build Hiscaries.sln

      - name: Test
        working-directory: server
        run: dotnet test Hiscaries.sln --no-build --verbosity normal
