name: Angular Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Clean install dependencies
        working-directory: client
        run: npm ci

      - name: Run tests
        working-directory: client
        run: npm run test:ci -- --browsers=ChromeHeadless
        env:
          DISPLAY: :99
          CHROME_BIN: /usr/bin/chromium-browser
          CHROME_HEADLESS_NO_SANDBOX: true

      - name: Build the project
        working-directory: client
        run: npm run build -- --prod
